language: node_js

services:
  - postgresql

env:
  - POSTGRES_URL=postgres://postgres@localhost:5432/postgres_driver

node_js:
  - 6.11.0

before_install:
  - psql -c 'create database postgres_driver owner postgres;' -U postgres
  - psql -c 'create table users (id int NOT NULL PRIMARY KEY, name text NOT NULL, verified boolean NOT NULL);' -U postgres -d postgres_driver
  - npm install
  - npm install typescript

script:
  - npm run build
  - npm run test